# Generated by Django 3.1.4 on 2021-01-03 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_nations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nations',
            new_name='Nation',
        ),
    ]
